### ISSUE TITLE
[Feature Request] Notes Section

### ISSUE THREAD

**Issue by Justinzobel** [adamrehn/gen-invoice#2]
Me again :)

Is it possible to easily add a notes section down the bottom.

I just want to easily add something like:
Thank you for your business!
Please send payment confirmation to email@address.com

**Comment by adamrehn** [comment]
Yes, you can control the output completely by writing your own custom template and using that. See the [Writing templates](https://adamrehn.com/docs/gen-invoice/overview/writing-templates) page of the documentation for all the details.
