### ISSUE TITLE
Example PDF outputs?

### ISSUE THREAD

**Issue by mikalyoung** [adamrehn/gen-invoice#3]
Can you include some example output PDFs?

**Comment by adamrehn** [comment]
Given that gen-invoice is specifically designed to be used with [user-written templates](https://adamrehn.com/docs/gen-invoice/overview/writing-templates), I'm not sure how instructive example output files would be. Any sample output would be generated using the (deliberately very plain and barebones) default template, which means it would not be representative of the results that users can expect once they've written their own templates. If there was a gallery of example templates contributed by the community then that might provide a better idea of what's possible, but as it stands there isn't really an effective way to communicate the flexibility of the template system aside from simply stating that it's limited only by your imagination and your skills in writing HTML and CSS.
