### ISSUE TITLE
Invoice HTML as a string 

### ISSUE THREAD

**Issue by babutabhavya** [adamrehn/gen-invoice#5]
This is a requirement more than an issue. The InvoiceGenerator, generate method should be able to return the rendered html as a string.

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been drowning in work over the past few months and progress on addressing my GitHub backlog has been frustratingly slow.

I've now added a `generate_string()` method to the `InvoiceGenerator` class that will return the generated HTML as a string. The change is live in gen-invoice version 0.0.3.
